### ISSUE TITLE
Separate Files with build step

### ISSUE THREAD

**Issue by raytiley** [stefanpenner/layout-bin-packer#17]
So before we start adding any more strategies for bin packing we should get this project split out into separate files  so it is easier to work on. Having everything in one file right now makes it cumbersome when quickly scanning the code for specific methods.

@stefanpenner any guidance before I attempt this? Don't want to go down a road you want to avoid.

**Comment by shaunc** [comment]
Splitting up the tests and using a testing framework would be nice too. I prefer mocha (and could submit a PR with mocha tests if you like) But anything that makes test code more modular and readable would be great.

**Comment by stefanpenner** [comment]
Feel free to use mocha

**Comment by krisselden** [comment]
I need to add some new layouts so this would be very much appreciated, I would like to ship `ember-collection` with a number of columns/ fixed row height layout and number of columns/variable height layout, both easy refactoring of the fixed grid layout that support not having to relayout when the width changes and handle 'clientWidth' being smaller than the width.

**Comment by raytiley** [comment]
I'm working on this here: https://github.com/raytiley/layout-bin-packer/tree/ember-cli-build

**Comment by shaunc** [comment]
Hmm... just took a look. Layout-bin-packer is a pretty general purpose utility, isn't it? Isn't it a bit heavy handed to require ember or even phantomjs for test support. What if you want to use it in some other context?

... I guess the argument might be that this is a familiar way to get in-browser tests, but I thought it might warrant discussion.

**Comment by krisselden** [comment]
I'm just did a basic breakup with es6 modules and used rollup to produce the bundled umd output.
