### ISSUE TITLE
Need a new release on NPM

### ISSUE THREAD

**Issue by Alonski** [stefanpenner/layout-bin-packer#29]
The last release of this addon was in April... A lot has changed since then and while this repo has been keeping itself updated NPM still lists the version from a few months ago.

Now for addons not using ember-cli-babel v6 this deprecation pops up:
ember-learn/ember-api-docs#470

This is fixed in master.

Please release a new NPM release.

**Comment by stefanpenner** [comment]
released as v1.4.0 🎉

**Comment by Alonski** [comment]
Thanks!
