### ISSUE TITLE
visibleStartingIndex

### ISSUE THREAD

**Issue by shaunc** [stefanpenner/layout-bin-packer#9]
There is a semantic clash in "visibleStartingIndex" which is causing problems in https://github.com/shaunc/ember-collection, on whose tests I am working.

Here is a picture :) --

![image](https://cloud.githubusercontent.com/assets/193170/9266259/e55fb534-423e-11e5-81ad-a3e0c0318e4f.png)

What is going on is that we are displaying 5 items with a fixed grid, each 50x50 in a window 150 wide by 500 tall. The test sets the y-offset to 100, and there is a 5 item "buffer".

In a long list, this would mean that the starting position is on the 6th element. However, since the list easily fits in the available space, it is displayed from the start. To produce the display as shown, ember-list starts at item 6, and counts back 5 items (the buffer). Thus the first item is outside of the buffer and is turned off.

The point is that _actually_ the first visible item is the 1st one, as the content box has more than enough space and won't scroll despite the y-offset.

The question is whether to correct it in layout-bin-packer or in ember-list. I thought I'd bring it up with you and @mmun.

**Comment by stefanpenner** [comment]
> layout-bin-packer

I believe it would be best addressed here, it seems like the "count back from 6" should have been clamped at maxLength.

**Comment by shaunc** [comment]
You then need to take viewport height into consideration as well then in "visibleStartingIndex". 
[NB https://github.com/shaunc/ember-collection/tree/phantom-offset includes failing test -- I'd be happy to add a few failing tests here if you'd like. :)]

**Comment by shaunc** [comment]
Hmm... its late here (writing from Poland)... but as far as I can see you cant just stop at the max length. Rather you need to know if you have enough scroll space to accommodate the given offset by filling forward to the given viewport height. (putatively given -- it isn't given yet).

**Comment by tim-evans** [comment]
@shaunc I'm responsible for https://github.com/stefanpenner/layout-bin-packer/blob/master/index.js#L262-L322 :trollface: 

See https://github.com/stefanpenner/layout-bin-packer/pull/2 for more information about the algorithm and such.

**Comment by shaunc** [comment]
@tim-evans -- the current problem occurs even in the fixed grid case. Naively, you want to calculate a maximum scroll offset by figuring out how big the content box really is (relative to the viewport), then limiting a passed in offset to whatever that maximum is. I didn't actually check if this is a bug in the  "ShelfFirst" case.
